language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
  - gem install sass
  - gem install compass
install:
  - npm install -g npm@2
  - npm install
  - bower install
before_script: grunt build
services:
  - mongodb
sudo: required
